name = "automate-cf-proxy"
type = "webpack"
account_id = "($WRANGLER_ACCOUNT_ID)"
workers_dev = true
route = ""
zone_id = ""
webpack_config = "webpack.config.js"
kv_namespaces = [
  { binding = "AUTOMATE_PROXY_KV", id = "($WRANGLER_KV_ID)", preview_id = "($WRANGLER_KV_PREVIEW_ID)" }
]

[env.production]
name = "automate-proxy"
route = "rpc.chronologic.network/*"
account_id = "($WRANGLER_ACCOUNT_ID)"
zone_id = "($WRANGLER_ZONE_ID)"
webpack_config = "webpack.prod.js"

[env.staging]
name = "automate-proxy-ropsten"

[dev]
port=1337
