# variables following ($THIS_FORMAT) will be replaced with env variables by buildWranglerToml.js

name = "automate-proxy"
compatibility_date = "2022-05-20"
account_id = "($WRANGLER_ACCOUNT_ID)"
route = "rpc.chronologic.network/*"
main = "src/index.ts"
workers_dev = true
node_compat = true

[[kv_namespaces]]
binding = "AUTOMATE_PROXY_KV"
id = "($WRANGLER_KV_ID)"
preview_id = "($WRANGLER_KV_PREVIEW_ID)"

# this whole section will be autopopulated by buildWranglerToml.js
[vars]


[dev]
port=1337
