name = "automate-cf-proxy"
type = "webpack"
account_id = "d03e586dc372d50234c45b43b62bf1ea"
workers_dev = true
route = ""
zone_id = ""
webpack_config = "webpack.config.js"

[env.production]
name = "automate-proxy"
route = "rpc.chronologic.network/*"
account_id = "45b43575cc04812bac012c7cb9e01787"
zone_id = "a215759d6bf8da898fc89f77570b42df"
webpack_config = "webpack.prod.js"

[env.staging]
name = "automate-proxy-ropsten"

[dev]
port=1337
